brave_de_project:
  target: dev
  
  outputs:
    dev:
      type: snowflake
      account: QDLMHKH-FM67721
      user: PROJECT_LEARNER_CHRIS_W2
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      # User/password auth
      database: BRAVE_DATABASE
      warehouse: BRAVE_WAREHOUSE
      threads: 1
      schema: PROJECT_TEST
      client_session_keep_alive: False
      query_tag: dbt
